version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: FriendDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./sql/frienddb.sql:/docker-entrypoint-initdb.d/frienddb.sql
    ports:
      - "5432:5432"

  app:
    image: friend-management-system:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/FriendDB
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 12345678

volumes:
  frienddb_data:
